name: kib
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  neuomorphic_container: ^2.0.3
  flutter_neumorphic: ^3.0.3
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.1.0
  cloud_firestore: ^2.2.0
  country_code_picker: ^2.0.1
  quiver: ^3.0.1
  image_picker: ^0.7.5+3
  mpesa_flutter_plugin: ^1.0.0
  cloud_functions: ^1.1.0
  provider: ^5.0.0
  string_validator: ^0.3.0
  http: ^0.13.3
  animate_do: ^2.0.0
  font_awesome_flutter: ^9.0.0
  geoflutterfire: ^3.0.0-nullsafety.4
  location: ^4.1.1
  js: ^0.6.3
  flutter_local_notifications: ^6.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "assets/images/whitebg.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf

